# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterdialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from .MagPy4UI import TimeEdit

class CheckBoxList(QtWidgets.QListWidget):
    ''' ListWidget with checkable items '''
    def addItem(self, *arg ,**kwargs):
        super().addItem(*arg, **kwargs)
        item = self.getItems()[-1]
        item.setFlags(item.flags() | QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Unchecked)

    def getItems(self):
        ''' Get listwidgetitems '''
        count = self.count()
        items = [self.item(row) for row in range(count)]
        return items

    def getCheckedItems(self):
        ''' Get checked values '''
        checked = QtCore.Qt.Checked
        return [item.text() for item in self.getItems() if item.checkState() == checked]

    def setItemChecked(self, index):
        self.getItems()[index].setCheckState(QtCore.Qt.Checked)

class Ui_filterdialog(object):
    def setupUi(self, filterdialog):
        filterdialog.setObjectName("filterdialog")
        filterdialog.resize(690, 442)
        filterdialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(filterdialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.windowTypeGroupBox = QtWidgets.QGroupBox(filterdialog)
        self.windowTypeGroupBox.setGeometry(QtCore.QRect(10, 240, 450, 150))
        self.windowTypeGroupBox.setObjectName("windowTypeGroupBox")
        self.windowTypeComboBox = QtWidgets.QComboBox(self.windowTypeGroupBox)
        self.windowTypeComboBox.setGeometry(QtCore.QRect(10, 20, 120, 20))
        self.windowTypeComboBox.setObjectName("windowTypeComboBox")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.windowTypeComboBox.addItem("")
        self.stopBandAttenuationUnit = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.stopBandAttenuationUnit.setGeometry(QtCore.QRect(420, 50, 20, 20))
        self.stopBandAttenuationUnit.setObjectName("stopBandAttenuationUnit")
        self.rippleUnit = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.rippleUnit.setGeometry(QtCore.QRect(420, 80, 20, 20))
        self.rippleUnit.setObjectName("rippleUnit")
        self.transitionWidthUnit = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.transitionWidthUnit.setGeometry(QtCore.QRect(420, 110, 20, 20))
        self.transitionWidthUnit.setObjectName("transitionWidthUnit")
        self.transitionWidthText = QtWidgets.QLineEdit(self.windowTypeGroupBox)
        self.transitionWidthText.setGeometry(QtCore.QRect(290, 110, 120, 20))
        self.transitionWidthText.setObjectName("transitionWidthText")
        self.transitionWidthLabel = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.transitionWidthLabel.setGeometry(QtCore.QRect(150, 110, 120, 20))
        self.transitionWidthLabel.setObjectName("transitionWidthLabel")
        self.rippleText = QtWidgets.QLineEdit(self.windowTypeGroupBox)
        self.rippleText.setGeometry(QtCore.QRect(290, 80, 120, 20))
        self.rippleText.setObjectName("rippleText")
        self.rippleLabel = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.rippleLabel.setGeometry(QtCore.QRect(150, 80, 120, 20))
        self.rippleLabel.setObjectName("rippleLabel")
        self.stopBandAttenuationLabel = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.stopBandAttenuationLabel.setGeometry(QtCore.QRect(150, 50, 120, 20))
        self.stopBandAttenuationLabel.setObjectName("stopBandAttenuationLabel")
        self.stopBandAttenuationText = QtWidgets.QLineEdit(self.windowTypeGroupBox)
        self.stopBandAttenuationText.setGeometry(QtCore.QRect(290, 50, 120, 20))
        self.stopBandAttenuationText.setObjectName("stopBandAttenuationText")
        self.alphaLabel = QtWidgets.QLabel(self.windowTypeGroupBox)
        self.alphaLabel.setGeometry(QtCore.QRect(150, 20, 120, 20))
        self.alphaLabel.setObjectName("alphaLabel")
        self.alphaText = QtWidgets.QLineEdit(self.windowTypeGroupBox)
        self.alphaText.setGeometry(QtCore.QRect(290, 20, 120, 20))
        self.alphaText.setObjectName("alphaText")
        self.filterTypeGroupBox = QtWidgets.QGroupBox(filterdialog)
        self.filterTypeGroupBox.setGeometry(QtCore.QRect(10, 10, 451, 120))
        self.filterTypeGroupBox.setObjectName("filterTypeGroupBox")
        self.filterTypeComboBox = QtWidgets.QComboBox(self.filterTypeGroupBox)
        self.filterTypeComboBox.setGeometry(QtCore.QRect(10, 20, 120, 20))
        self.filterTypeComboBox.setObjectName("filterTypeComboBox")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.lowCutoffFreqUnit = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.lowCutoffFreqUnit.setGeometry(QtCore.QRect(420, 20, 20, 20))
        self.lowCutoffFreqUnit.setObjectName("lowCutoffFreqUnit")
        self.highCutoffFreqUnit = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.highCutoffFreqUnit.setGeometry(QtCore.QRect(420, 50, 20, 20))
        self.highCutoffFreqUnit.setObjectName("highCutoffFreqUnit")
        self.highCutoffFreqLabel = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.highCutoffFreqLabel.setGeometry(QtCore.QRect(150, 50, 120, 20))
        self.highCutoffFreqLabel.setObjectName("highCutoffFreqLabel")
        self.highCutoffFreqText = QtWidgets.QLineEdit(self.filterTypeGroupBox)
        self.highCutoffFreqText.setGeometry(QtCore.QRect(290, 50, 120, 20))
        self.highCutoffFreqText.setObjectName("highCutoffFreqText")
        self.lowCutoffFreqLabel = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.lowCutoffFreqLabel.setGeometry(QtCore.QRect(150, 20, 120, 20))
        self.lowCutoffFreqLabel.setObjectName("lowCutoffFreqLabel")
        self.lowCutoffFreqText = QtWidgets.QLineEdit(self.filterTypeGroupBox)
        self.lowCutoffFreqText.setGeometry(QtCore.QRect(290, 20, 120, 20))
        self.lowCutoffFreqText.setObjectName("lowCutoffFreqText")
        self.nyquistFreqLabel = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.nyquistFreqLabel.setGeometry(QtCore.QRect(150, 80, 120, 20))
        self.nyquistFreqLabel.setObjectName("nyquistFreqLabel")
        self.nyquistFreqText = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.nyquistFreqText.setGeometry(QtCore.QRect(290, 80, 120, 20))
        self.nyquistFreqText.setText("")
        self.nyquistFreqText.setIndent(3)
        self.nyquistFreqText.setObjectName("nyquistFreqText")
        self.nyquistFreqUnit = QtWidgets.QLabel(self.filterTypeGroupBox)
        self.nyquistFreqUnit.setGeometry(QtCore.QRect(420, 80, 20, 20))
        self.nyquistFreqUnit.setObjectName("nyquistFreqUnit")
        self.filterWidthGroupBox = QtWidgets.QGroupBox(filterdialog)
        self.filterWidthGroupBox.setGeometry(QtCore.QRect(10, 140, 450, 90))
        self.filterWidthGroupBox.setObjectName("filterWidthGroupBox")
        self.filterWidthComboBox = QtWidgets.QComboBox(self.filterWidthGroupBox)
        self.filterWidthComboBox.setGeometry(QtCore.QRect(10, 20, 120, 20))
        self.filterWidthComboBox.setObjectName("filterWidthComboBox")
        self.filterWidthComboBox.addItem("")
        self.filterWidthComboBox.addItem("")
        self.numPointsLabel = QtWidgets.QLabel(self.filterWidthGroupBox)
        self.numPointsLabel.setGeometry(QtCore.QRect(150, 20, 120, 20))
        self.numPointsLabel.setObjectName("numPointsLabel")
        self.numPointsText = QtWidgets.QLineEdit(self.filterWidthGroupBox)
        self.numPointsText.setGeometry(QtCore.QRect(290, 20, 120, 20))
        self.numPointsText.setObjectName("numPointsText")
        self.timespanLabel = QtWidgets.QLabel(self.filterWidthGroupBox)
        self.timespanLabel.setGeometry(QtCore.QRect(150, 50, 120, 20))
        self.timespanLabel.setObjectName("timespanLabel")
        self.timespanText = QtWidgets.QLineEdit(self.filterWidthGroupBox)
        self.timespanText.setGeometry(QtCore.QRect(290, 50, 120, 20))
        self.timespanText.setObjectName("timespanText")
        self.timespanUnit = QtWidgets.QLabel(self.filterWidthGroupBox)
        self.timespanUnit.setGeometry(QtCore.QRect(420, 50, 20, 20))
        self.timespanUnit.setObjectName("timespanUnit")

        # Set up variable selection
        self.varFrame = QtWidgets.QFrame(filterdialog)
        self.varFrame.setGeometry(QtCore.QRect(460, 0, 220, 400))
        self.varList = CheckBoxList()

        varLt = QtWidgets.QVBoxLayout(self.varFrame)
        varLt.addWidget(QtWidgets.QLabel('Variables'))
        varLt.addWidget(self.varList)

        # Set up time edits
        timeEditFrame = QtWidgets.QFrame(filterdialog)
        timeLt = QtWidgets.QHBoxLayout(timeEditFrame)
        timeLt.setContentsMargins(0, 0, 0, 0)
        self.timeEdit = TimeEdit()
        self.timeEdit.setFont(QtGui.QFont())
        timeLt.addWidget(self.timeEdit.start)
        timeLt.addWidget(self.timeEdit.end)

        timeEditFrame.setGeometry(QtCore.QRect(0, 365, 455, 100))

        self.retranslateUi(filterdialog)
        self.buttonBox.accepted.connect(filterdialog.accept)
        self.buttonBox.rejected.connect(filterdialog.reject)
        QtCore.QMetaObject.connectSlotsByName(filterdialog)
        filterdialog.setTabOrder(self.filterTypeComboBox, self.lowCutoffFreqText)
        filterdialog.setTabOrder(self.lowCutoffFreqText, self.highCutoffFreqText)
        filterdialog.setTabOrder(self.highCutoffFreqText, self.filterWidthComboBox)
        filterdialog.setTabOrder(self.filterWidthComboBox, self.numPointsText)
        filterdialog.setTabOrder(self.numPointsText, self.timespanText)
        filterdialog.setTabOrder(self.timespanText, self.windowTypeComboBox)
        filterdialog.setTabOrder(self.windowTypeComboBox, self.alphaText)
        filterdialog.setTabOrder(self.alphaText, self.stopBandAttenuationText)
        filterdialog.setTabOrder(self.stopBandAttenuationText, self.rippleText)
        filterdialog.setTabOrder(self.rippleText, self.transitionWidthText)

    def retranslateUi(self, filterdialog):
        _translate = QtCore.QCoreApplication.translate
        filterdialog.setWindowTitle(_translate("filterdialog", "Filter"))
        self.windowTypeGroupBox.setTitle(_translate("filterdialog", "Window Type"))
        self.windowTypeComboBox.setItemText(0, _translate("filterdialog", "Rectangular"))
        self.windowTypeComboBox.setItemText(1, _translate("filterdialog", "Triangular"))
        self.windowTypeComboBox.setItemText(2, _translate("filterdialog", "Hamming"))
        self.windowTypeComboBox.setItemText(3, _translate("filterdialog", "Hanning"))
        self.windowTypeComboBox.setItemText(4, _translate("filterdialog", "Kaiser"))
        self.windowTypeComboBox.setItemText(5, _translate("filterdialog", "Chebyshev"))
        self.stopBandAttenuationUnit.setText(_translate("filterdialog", "dB"))
        self.rippleUnit.setText(_translate("filterdialog", "dB"))
        self.transitionWidthUnit.setText(_translate("filterdialog", "Hz"))
        self.transitionWidthLabel.setText(_translate("filterdialog", "Transition Width:"))
        self.rippleLabel.setText(_translate("filterdialog", "Ripple:"))
        self.stopBandAttenuationLabel.setText(_translate("filterdialog", "Stop Band Attenuation:"))
        self.alphaLabel.setText(_translate("filterdialog", "Alpha:"))
        self.filterTypeGroupBox.setTitle(_translate("filterdialog", "Filter Type"))
        self.filterTypeComboBox.setItemText(0, _translate("filterdialog", "Low Pass"))
        self.filterTypeComboBox.setItemText(1, _translate("filterdialog", "High Pass"))
        self.filterTypeComboBox.setItemText(2, _translate("filterdialog", "Band Pass"))
        self.filterTypeComboBox.setItemText(3, _translate("filterdialog", "Band Stop"))
        self.lowCutoffFreqUnit.setText(_translate("filterdialog", "Hz"))
        self.highCutoffFreqUnit.setText(_translate("filterdialog", "Hz"))
        self.highCutoffFreqLabel.setText(_translate("filterdialog", "High Cutoff Frequency:"))
        self.lowCutoffFreqLabel.setText(_translate("filterdialog", "Low Cutoff Frequency:"))
        self.nyquistFreqLabel.setText(_translate("filterdialog", "Nyquist frequency:"))
        self.nyquistFreqUnit.setText(_translate("filterdialog", "Hz"))
        self.filterWidthGroupBox.setTitle(_translate("filterdialog", "Filter Width"))
        self.filterWidthComboBox.setItemText(0, _translate("filterdialog", "Points"))
        self.filterWidthComboBox.setItemText(1, _translate("filterdialog", "Time"))
        self.numPointsLabel.setText(_translate("filterdialog", "Number of Points:"))
        self.timespanLabel.setText(_translate("filterdialog", "Timespan:"))
        self.timespanUnit.setText(_translate("filterdialog", "s"))

