# This is a basic workflow to help you get started with Actions

name: pip-release2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ wfs ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Get version tag
        run: |
          git fetch --prune --unshallow
          version=$(cat MagPy4/version.txt)
          version_tag=v$version
          name="MagPy4 v$version"
          echo 'vtag='$version_tag >> $GITHUB_ENV
          echo 'vtagname='$name >> $GITHUB_ENV
      - run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/igpp-ucla/mp-releases/releases \
          --user ":${{ env.GITHUB_TOKEN }}" -d '{"tag_name":"test"}'
      - uses: ncipollo/release-action@v1.8.6
        with:
          tag: ${{ env.vtag }}
          name: ${{ env.vtagname }}
          token: ${{ env.GITHUB_TOKEN }}
          repo: mp-releases
          owner: igpp-ucla
